version: "3"
services:
  ###POSTGRESS Inventory
    db-inventory:
      container_name: db-inventory
      image: postgres:15.2
      restart: unless-stopped
      environment:
        POSTGRES_DB: ms_inventory
        POSTGRES_USER: root
        POSTGRES_PASSWORD: 12345
      ports:
        - "5431:5431"
      expose:
        - "5431"
      command:
        - p 5431

###MYSQL ORDERS
    db-orders:
      container_name: db-orders
      image: mysql:8.0.33
      restart: unless-stopped
      environment:
        MYSQL_DATABASE: ms_orders
        MYSQL_USER: pablo
        MYSQL_PASSWORD: 12345
        MYSQL_ROOT_PASSWORD: 12345
      ports:
        - "3306:3306"
      expose:
        - "3306"
  ###POSTGRESS PRODUCTS
    db-products:
      container_name: db-products
      image: postgres:15.2
      restart: unless-stopped
      environment:
        POSTGRES_DB: ms_products
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 12345
      ports:
        - "5432:5432"
      expose:
        - "5432"
      command:
        - p 5432